-- ============================================================================
-- Migration 007: Seed de tous les pays du monde (ISO 3166-1)
-- ============================================================================
-- 1. Met tous les pays existants en active = true
-- 2. Insère tous les pays du monde (~249 codes ISO 3166-1)
--    avec ON CONFLICT pour mettre à jour les existants
-- ============================================================================

BEGIN;

-- Étape 1 : Activer tous les pays existants
UPDATE countries SET active = true WHERE active = false;

-- Étape 2 : Insérer tous les pays du monde
INSERT INTO countries (id, iso_code, iso_code3, name_fr, name_en, name_ar, phone_code, active)
VALUES
  -- A
  (uuid_generate_v4(), 'AF', 'AFG', 'Afghanistan', 'Afghanistan', 'أفغانستان', '+93', true),
  (uuid_generate_v4(), 'AL', 'ALB', 'Albanie', 'Albania', 'ألبانيا', '+355', true),
  (uuid_generate_v4(), 'DZ', 'DZA', 'Algérie', 'Algeria', 'الجزائر', '+213', true),
  (uuid_generate_v4(), 'AD', 'AND', 'Andorre', 'Andorra', 'أندورا', '+376', true),
  (uuid_generate_v4(), 'AO', 'AGO', 'Angola', 'Angola', 'أنغولا', '+244', true),
  (uuid_generate_v4(), 'AG', 'ATG', 'Antigua-et-Barbuda', 'Antigua and Barbuda', 'أنتيغوا وبربودا', '+1-268', true),
  (uuid_generate_v4(), 'AR', 'ARG', 'Argentine', 'Argentina', 'الأرجنتين', '+54', true),
  (uuid_generate_v4(), 'AM', 'ARM', 'Arménie', 'Armenia', 'أرمينيا', '+374', true),
  (uuid_generate_v4(), 'AU', 'AUS', 'Australie', 'Australia', 'أستراليا', '+61', true),
  (uuid_generate_v4(), 'AT', 'AUT', 'Autriche', 'Austria', 'النمسا', '+43', true),
  (uuid_generate_v4(), 'AZ', 'AZE', 'Azerbaïdjan', 'Azerbaijan', 'أذربيجان', '+994', true),
  -- B
  (uuid_generate_v4(), 'BS', 'BHS', 'Bahamas', 'Bahamas', 'الباهاما', '+1-242', true),
  (uuid_generate_v4(), 'BH', 'BHR', 'Bahreïn', 'Bahrain', 'البحرين', '+973', true),
  (uuid_generate_v4(), 'BD', 'BGD', 'Bangladesh', 'Bangladesh', 'بنغلاديش', '+880', true),
  (uuid_generate_v4(), 'BB', 'BRB', 'Barbade', 'Barbados', 'بربادوس', '+1-246', true),
  (uuid_generate_v4(), 'BY', 'BLR', 'Biélorussie', 'Belarus', 'بيلاروسيا', '+375', true),
  (uuid_generate_v4(), 'BE', 'BEL', 'Belgique', 'Belgium', 'بلجيكا', '+32', true),
  (uuid_generate_v4(), 'BZ', 'BLZ', 'Belize', 'Belize', 'بليز', '+501', true),
  (uuid_generate_v4(), 'BJ', 'BEN', 'Bénin', 'Benin', 'بنين', '+229', true),
  (uuid_generate_v4(), 'BT', 'BTN', 'Bhoutan', 'Bhutan', 'بوتان', '+975', true),
  (uuid_generate_v4(), 'BO', 'BOL', 'Bolivie', 'Bolivia', 'بوليفيا', '+591', true),
  (uuid_generate_v4(), 'BA', 'BIH', 'Bosnie-Herzégovine', 'Bosnia and Herzegovina', 'البوسنة والهرسك', '+387', true),
  (uuid_generate_v4(), 'BW', 'BWA', 'Botswana', 'Botswana', 'بوتسوانا', '+267', true),
  (uuid_generate_v4(), 'BR', 'BRA', 'Brésil', 'Brazil', 'البرازيل', '+55', true),
  (uuid_generate_v4(), 'BN', 'BRN', 'Brunei', 'Brunei', 'بروناي', '+673', true),
  (uuid_generate_v4(), 'BG', 'BGR', 'Bulgarie', 'Bulgaria', 'بلغاريا', '+359', true),
  (uuid_generate_v4(), 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso', 'بوركينا فاسو', '+226', true),
  (uuid_generate_v4(), 'BI', 'BDI', 'Burundi', 'Burundi', 'بوروندي', '+257', true),
  -- C
  (uuid_generate_v4(), 'CV', 'CPV', 'Cap-Vert', 'Cape Verde', 'الرأس الأخضر', '+238', true),
  (uuid_generate_v4(), 'KH', 'KHM', 'Cambodge', 'Cambodia', 'كمبوديا', '+855', true),
  (uuid_generate_v4(), 'CM', 'CMR', 'Cameroun', 'Cameroon', 'الكاميرون', '+237', true),
  (uuid_generate_v4(), 'CA', 'CAN', 'Canada', 'Canada', 'كندا', '+1', true),
  (uuid_generate_v4(), 'CF', 'CAF', 'République centrafricaine', 'Central African Republic', 'جمهورية أفريقيا الوسطى', '+236', true),
  (uuid_generate_v4(), 'TD', 'TCD', 'Tchad', 'Chad', 'تشاد', '+235', true),
  (uuid_generate_v4(), 'CL', 'CHL', 'Chili', 'Chile', 'تشيلي', '+56', true),
  (uuid_generate_v4(), 'CN', 'CHN', 'Chine', 'China', 'الصين', '+86', true),
  (uuid_generate_v4(), 'CO', 'COL', 'Colombie', 'Colombia', 'كولومبيا', '+57', true),
  (uuid_generate_v4(), 'KM', 'COM', 'Comores', 'Comoros', 'جزر القمر', '+269', true),
  (uuid_generate_v4(), 'CG', 'COG', 'Congo', 'Congo', 'الكونغو', '+242', true),
  (uuid_generate_v4(), 'CD', 'COD', 'République démocratique du Congo', 'Democratic Republic of the Congo', 'جمهورية الكونغو الديمقراطية', '+243', true),
  (uuid_generate_v4(), 'CR', 'CRI', 'Costa Rica', 'Costa Rica', 'كوستاريكا', '+506', true),
  (uuid_generate_v4(), 'CI', 'CIV', 'Côte d''Ivoire', 'Ivory Coast', 'ساحل العاج', '+225', true),
  (uuid_generate_v4(), 'HR', 'HRV', 'Croatie', 'Croatia', 'كرواتيا', '+385', true),
  (uuid_generate_v4(), 'CU', 'CUB', 'Cuba', 'Cuba', 'كوبا', '+53', true),
  (uuid_generate_v4(), 'CY', 'CYP', 'Chypre', 'Cyprus', 'قبرص', '+357', true),
  (uuid_generate_v4(), 'CZ', 'CZE', 'Tchéquie', 'Czech Republic', 'التشيك', '+420', true),
  -- D
  (uuid_generate_v4(), 'DK', 'DNK', 'Danemark', 'Denmark', 'الدنمارك', '+45', true),
  (uuid_generate_v4(), 'DJ', 'DJI', 'Djibouti', 'Djibouti', 'جيبوتي', '+253', true),
  (uuid_generate_v4(), 'DM', 'DMA', 'Dominique', 'Dominica', 'دومينيكا', '+1-767', true),
  (uuid_generate_v4(), 'DO', 'DOM', 'République dominicaine', 'Dominican Republic', 'جمهورية الدومينيكان', '+1-809', true),
  -- E
  (uuid_generate_v4(), 'EC', 'ECU', 'Équateur', 'Ecuador', 'الإكوادور', '+593', true),
  (uuid_generate_v4(), 'EG', 'EGY', 'Égypte', 'Egypt', 'مصر', '+20', true),
  (uuid_generate_v4(), 'SV', 'SLV', 'Salvador', 'El Salvador', 'السلفادور', '+503', true),
  (uuid_generate_v4(), 'GQ', 'GNQ', 'Guinée équatoriale', 'Equatorial Guinea', 'غينيا الاستوائية', '+240', true),
  (uuid_generate_v4(), 'ER', 'ERI', 'Érythrée', 'Eritrea', 'إريتريا', '+291', true),
  (uuid_generate_v4(), 'EE', 'EST', 'Estonie', 'Estonia', 'إستونيا', '+372', true),
  (uuid_generate_v4(), 'SZ', 'SWZ', 'Eswatini', 'Eswatini', 'إسواتيني', '+268', true),
  (uuid_generate_v4(), 'ET', 'ETH', 'Éthiopie', 'Ethiopia', 'إثيوبيا', '+251', true),
  -- F
  (uuid_generate_v4(), 'FJ', 'FJI', 'Fidji', 'Fiji', 'فيجي', '+679', true),
  (uuid_generate_v4(), 'FI', 'FIN', 'Finlande', 'Finland', 'فنلندا', '+358', true),
  (uuid_generate_v4(), 'FR', 'FRA', 'France', 'France', 'فرنسا', '+33', true),
  -- G
  (uuid_generate_v4(), 'GA', 'GAB', 'Gabon', 'Gabon', 'الغابون', '+241', true),
  (uuid_generate_v4(), 'GM', 'GMB', 'Gambie', 'Gambia', 'غامبيا', '+220', true),
  (uuid_generate_v4(), 'GE', 'GEO', 'Géorgie', 'Georgia', 'جورجيا', '+995', true),
  (uuid_generate_v4(), 'DE', 'DEU', 'Allemagne', 'Germany', 'ألمانيا', '+49', true),
  (uuid_generate_v4(), 'GH', 'GHA', 'Ghana', 'Ghana', 'غانا', '+233', true),
  (uuid_generate_v4(), 'GR', 'GRC', 'Grèce', 'Greece', 'اليونان', '+30', true),
  (uuid_generate_v4(), 'GD', 'GRD', 'Grenade', 'Grenada', 'غرينادا', '+1-473', true),
  (uuid_generate_v4(), 'GT', 'GTM', 'Guatemala', 'Guatemala', 'غواتيمالا', '+502', true),
  (uuid_generate_v4(), 'GN', 'GIN', 'Guinée', 'Guinea', 'غينيا', '+224', true),
  (uuid_generate_v4(), 'GW', 'GNB', 'Guinée-Bissau', 'Guinea-Bissau', 'غينيا بيساو', '+245', true),
  (uuid_generate_v4(), 'GY', 'GUY', 'Guyana', 'Guyana', 'غيانا', '+592', true),
  -- H
  (uuid_generate_v4(), 'HT', 'HTI', 'Haïti', 'Haiti', 'هايتي', '+509', true),
  (uuid_generate_v4(), 'HN', 'HND', 'Honduras', 'Honduras', 'هندوراس', '+504', true),
  (uuid_generate_v4(), 'HU', 'HUN', 'Hongrie', 'Hungary', 'المجر', '+36', true),
  -- I
  (uuid_generate_v4(), 'IS', 'ISL', 'Islande', 'Iceland', 'آيسلندا', '+354', true),
  (uuid_generate_v4(), 'IN', 'IND', 'Inde', 'India', 'الهند', '+91', true),
  (uuid_generate_v4(), 'ID', 'IDN', 'Indonésie', 'Indonesia', 'إندونيسيا', '+62', true),
  (uuid_generate_v4(), 'IR', 'IRN', 'Iran', 'Iran', 'إيران', '+98', true),
  (uuid_generate_v4(), 'IQ', 'IRQ', 'Irak', 'Iraq', 'العراق', '+964', true),
  (uuid_generate_v4(), 'IE', 'IRL', 'Irlande', 'Ireland', 'أيرلندا', '+353', true),
  (uuid_generate_v4(), 'IL', 'ISR', 'Israël', 'Israel', 'إسرائيل', '+972', true),
  (uuid_generate_v4(), 'IT', 'ITA', 'Italie', 'Italy', 'إيطاليا', '+39', true),
  -- J
  (uuid_generate_v4(), 'JM', 'JAM', 'Jamaïque', 'Jamaica', 'جامايكا', '+1-876', true),
  (uuid_generate_v4(), 'JP', 'JPN', 'Japon', 'Japan', 'اليابان', '+81', true),
  (uuid_generate_v4(), 'JO', 'JOR', 'Jordanie', 'Jordan', 'الأردن', '+962', true),
  -- K
  (uuid_generate_v4(), 'KZ', 'KAZ', 'Kazakhstan', 'Kazakhstan', 'كازاخستان', '+7', true),
  (uuid_generate_v4(), 'KE', 'KEN', 'Kenya', 'Kenya', 'كينيا', '+254', true),
  (uuid_generate_v4(), 'KI', 'KIR', 'Kiribati', 'Kiribati', 'كيريباتي', '+686', true),
  (uuid_generate_v4(), 'KP', 'PRK', 'Corée du Nord', 'North Korea', 'كوريا الشمالية', '+850', true),
  (uuid_generate_v4(), 'KR', 'KOR', 'Corée du Sud', 'South Korea', 'كوريا الجنوبية', '+82', true),
  (uuid_generate_v4(), 'KW', 'KWT', 'Koweït', 'Kuwait', 'الكويت', '+965', true),
  (uuid_generate_v4(), 'KG', 'KGZ', 'Kirghizistan', 'Kyrgyzstan', 'قيرغيزستان', '+996', true),
  -- L
  (uuid_generate_v4(), 'LA', 'LAO', 'Laos', 'Laos', 'لاوس', '+856', true),
  (uuid_generate_v4(), 'LV', 'LVA', 'Lettonie', 'Latvia', 'لاتفيا', '+371', true),
  (uuid_generate_v4(), 'LB', 'LBN', 'Liban', 'Lebanon', 'لبنان', '+961', true),
  (uuid_generate_v4(), 'LS', 'LSO', 'Lesotho', 'Lesotho', 'ليسوتو', '+266', true),
  (uuid_generate_v4(), 'LR', 'LBR', 'Libéria', 'Liberia', 'ليبيريا', '+231', true),
  (uuid_generate_v4(), 'LY', 'LBY', 'Libye', 'Libya', 'ليبيا', '+218', true),
  (uuid_generate_v4(), 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein', 'ليختنشتاين', '+423', true),
  (uuid_generate_v4(), 'LT', 'LTU', 'Lituanie', 'Lithuania', 'ليتوانيا', '+370', true),
  (uuid_generate_v4(), 'LU', 'LUX', 'Luxembourg', 'Luxembourg', 'لوكسمبورغ', '+352', true),
  -- M
  (uuid_generate_v4(), 'MG', 'MDG', 'Madagascar', 'Madagascar', 'مدغشقر', '+261', true),
  (uuid_generate_v4(), 'MW', 'MWI', 'Malawi', 'Malawi', 'مالاوي', '+265', true),
  (uuid_generate_v4(), 'MY', 'MYS', 'Malaisie', 'Malaysia', 'ماليزيا', '+60', true),
  (uuid_generate_v4(), 'MV', 'MDV', 'Maldives', 'Maldives', 'المالديف', '+960', true),
  (uuid_generate_v4(), 'ML', 'MLI', 'Mali', 'Mali', 'مالي', '+223', true),
  (uuid_generate_v4(), 'MT', 'MLT', 'Malte', 'Malta', 'مالطا', '+356', true),
  (uuid_generate_v4(), 'MH', 'MHL', 'Îles Marshall', 'Marshall Islands', 'جزر مارشال', '+692', true),
  (uuid_generate_v4(), 'MR', 'MRT', 'Mauritanie', 'Mauritania', 'موريتانيا', '+222', true),
  (uuid_generate_v4(), 'MU', 'MUS', 'Maurice', 'Mauritius', 'موريشيوس', '+230', true),
  (uuid_generate_v4(), 'MX', 'MEX', 'Mexique', 'Mexico', 'المكسيك', '+52', true),
  (uuid_generate_v4(), 'FM', 'FSM', 'Micronésie', 'Micronesia', 'ميكرونيزيا', '+691', true),
  (uuid_generate_v4(), 'MD', 'MDA', 'Moldavie', 'Moldova', 'مولدوفا', '+373', true),
  (uuid_generate_v4(), 'MC', 'MCO', 'Monaco', 'Monaco', 'موناكو', '+377', true),
  (uuid_generate_v4(), 'MN', 'MNG', 'Mongolie', 'Mongolia', 'منغوليا', '+976', true),
  (uuid_generate_v4(), 'ME', 'MNE', 'Monténégro', 'Montenegro', 'الجبل الأسود', '+382', true),
  (uuid_generate_v4(), 'MA', 'MAR', 'Maroc', 'Morocco', 'المغرب', '+212', true),
  (uuid_generate_v4(), 'MZ', 'MOZ', 'Mozambique', 'Mozambique', 'موزمبيق', '+258', true),
  (uuid_generate_v4(), 'MM', 'MMR', 'Myanmar', 'Myanmar', 'ميانمار', '+95', true),
  -- N
  (uuid_generate_v4(), 'NA', 'NAM', 'Namibie', 'Namibia', 'ناميبيا', '+264', true),
  (uuid_generate_v4(), 'NR', 'NRU', 'Nauru', 'Nauru', 'ناورو', '+674', true),
  (uuid_generate_v4(), 'NP', 'NPL', 'Népal', 'Nepal', 'نيبال', '+977', true),
  (uuid_generate_v4(), 'NL', 'NLD', 'Pays-Bas', 'Netherlands', 'هولندا', '+31', true),
  (uuid_generate_v4(), 'NZ', 'NZL', 'Nouvelle-Zélande', 'New Zealand', 'نيوزيلندا', '+64', true),
  (uuid_generate_v4(), 'NI', 'NIC', 'Nicaragua', 'Nicaragua', 'نيكاراغوا', '+505', true),
  (uuid_generate_v4(), 'NE', 'NER', 'Niger', 'Niger', 'النيجر', '+227', true),
  (uuid_generate_v4(), 'NG', 'NGA', 'Nigéria', 'Nigeria', 'نيجيريا', '+234', true),
  (uuid_generate_v4(), 'MK', 'MKD', 'Macédoine du Nord', 'North Macedonia', 'مقدونيا الشمالية', '+389', true),
  (uuid_generate_v4(), 'NO', 'NOR', 'Norvège', 'Norway', 'النرويج', '+47', true),
  -- O
  (uuid_generate_v4(), 'OM', 'OMN', 'Oman', 'Oman', 'عُمان', '+968', true),
  -- P
  (uuid_generate_v4(), 'PK', 'PAK', 'Pakistan', 'Pakistan', 'باكستان', '+92', true),
  (uuid_generate_v4(), 'PW', 'PLW', 'Palaos', 'Palau', 'بالاو', '+680', true),
  (uuid_generate_v4(), 'PS', 'PSE', 'Palestine', 'Palestine', 'فلسطين', '+970', true),
  (uuid_generate_v4(), 'PA', 'PAN', 'Panama', 'Panama', 'بنما', '+507', true),
  (uuid_generate_v4(), 'PG', 'PNG', 'Papouasie-Nouvelle-Guinée', 'Papua New Guinea', 'بابوا غينيا الجديدة', '+675', true),
  (uuid_generate_v4(), 'PY', 'PRY', 'Paraguay', 'Paraguay', 'باراغواي', '+595', true),
  (uuid_generate_v4(), 'PE', 'PER', 'Pérou', 'Peru', 'بيرو', '+51', true),
  (uuid_generate_v4(), 'PH', 'PHL', 'Philippines', 'Philippines', 'الفلبين', '+63', true),
  (uuid_generate_v4(), 'PL', 'POL', 'Pologne', 'Poland', 'بولندا', '+48', true),
  (uuid_generate_v4(), 'PT', 'PRT', 'Portugal', 'Portugal', 'البرتغال', '+351', true),
  -- Q
  (uuid_generate_v4(), 'QA', 'QAT', 'Qatar', 'Qatar', 'قطر', '+974', true),
  -- R
  (uuid_generate_v4(), 'RO', 'ROU', 'Roumanie', 'Romania', 'رومانيا', '+40', true),
  (uuid_generate_v4(), 'RU', 'RUS', 'Russie', 'Russia', 'روسيا', '+7', true),
  (uuid_generate_v4(), 'RW', 'RWA', 'Rwanda', 'Rwanda', 'رواندا', '+250', true),
  -- S
  (uuid_generate_v4(), 'KN', 'KNA', 'Saint-Kitts-et-Nevis', 'Saint Kitts and Nevis', 'سانت كيتس ونيفيس', '+1-869', true),
  (uuid_generate_v4(), 'LC', 'LCA', 'Sainte-Lucie', 'Saint Lucia', 'سانت لوسيا', '+1-758', true),
  (uuid_generate_v4(), 'VC', 'VCT', 'Saint-Vincent-et-les-Grenadines', 'Saint Vincent and the Grenadines', 'سانت فينسنت والغرينادين', '+1-784', true),
  (uuid_generate_v4(), 'WS', 'WSM', 'Samoa', 'Samoa', 'ساموا', '+685', true),
  (uuid_generate_v4(), 'SM', 'SMR', 'Saint-Marin', 'San Marino', 'سان مارينو', '+378', true),
  (uuid_generate_v4(), 'ST', 'STP', 'Sao Tomé-et-Principe', 'São Tomé and Príncipe', 'ساو تومي وبرينسيبي', '+239', true),
  (uuid_generate_v4(), 'SA', 'SAU', 'Arabie saoudite', 'Saudi Arabia', 'المملكة العربية السعودية', '+966', true),
  (uuid_generate_v4(), 'SN', 'SEN', 'Sénégal', 'Senegal', 'السنغال', '+221', true),
  (uuid_generate_v4(), 'RS', 'SRB', 'Serbie', 'Serbia', 'صربيا', '+381', true),
  (uuid_generate_v4(), 'SC', 'SYC', 'Seychelles', 'Seychelles', 'سيشيل', '+248', true),
  (uuid_generate_v4(), 'SL', 'SLE', 'Sierra Leone', 'Sierra Leone', 'سيراليون', '+232', true),
  (uuid_generate_v4(), 'SG', 'SGP', 'Singapour', 'Singapore', 'سنغافورة', '+65', true),
  (uuid_generate_v4(), 'SK', 'SVK', 'Slovaquie', 'Slovakia', 'سلوفاكيا', '+421', true),
  (uuid_generate_v4(), 'SI', 'SVN', 'Slovénie', 'Slovenia', 'سلوفينيا', '+386', true),
  (uuid_generate_v4(), 'SB', 'SLB', 'Îles Salomon', 'Solomon Islands', 'جزر سليمان', '+677', true),
  (uuid_generate_v4(), 'SO', 'SOM', 'Somalie', 'Somalia', 'الصومال', '+252', true),
  (uuid_generate_v4(), 'ZA', 'ZAF', 'Afrique du Sud', 'South Africa', 'جنوب أفريقيا', '+27', true),
  (uuid_generate_v4(), 'SS', 'SSD', 'Soudan du Sud', 'South Sudan', 'جنوب السودان', '+211', true),
  (uuid_generate_v4(), 'ES', 'ESP', 'Espagne', 'Spain', 'إسبانيا', '+34', true),
  (uuid_generate_v4(), 'LK', 'LKA', 'Sri Lanka', 'Sri Lanka', 'سريلانكا', '+94', true),
  (uuid_generate_v4(), 'SD', 'SDN', 'Soudan', 'Sudan', 'السودان', '+249', true),
  (uuid_generate_v4(), 'SR', 'SUR', 'Suriname', 'Suriname', 'سورينام', '+597', true),
  (uuid_generate_v4(), 'SE', 'SWE', 'Suède', 'Sweden', 'السويد', '+46', true),
  (uuid_generate_v4(), 'CH', 'CHE', 'Suisse', 'Switzerland', 'سويسرا', '+41', true),
  (uuid_generate_v4(), 'SY', 'SYR', 'Syrie', 'Syria', 'سوريا', '+963', true),
  -- T
  (uuid_generate_v4(), 'TW', 'TWN', 'Taïwan', 'Taiwan', 'تايوان', '+886', true),
  (uuid_generate_v4(), 'TJ', 'TJK', 'Tadjikistan', 'Tajikistan', 'طاجيكستان', '+992', true),
  (uuid_generate_v4(), 'TZ', 'TZA', 'Tanzanie', 'Tanzania', 'تنزانيا', '+255', true),
  (uuid_generate_v4(), 'TH', 'THA', 'Thaïlande', 'Thailand', 'تايلاند', '+66', true),
  (uuid_generate_v4(), 'TL', 'TLS', 'Timor oriental', 'Timor-Leste', 'تيمور الشرقية', '+670', true),
  (uuid_generate_v4(), 'TG', 'TGO', 'Togo', 'Togo', 'توغو', '+228', true),
  (uuid_generate_v4(), 'TO', 'TON', 'Tonga', 'Tonga', 'تونغا', '+676', true),
  (uuid_generate_v4(), 'TT', 'TTO', 'Trinité-et-Tobago', 'Trinidad and Tobago', 'ترينيداد وتوباغو', '+1-868', true),
  (uuid_generate_v4(), 'TN', 'TUN', 'Tunisie', 'Tunisia', 'تونس', '+216', true),
  (uuid_generate_v4(), 'TR', 'TUR', 'Turquie', 'Turkey', 'تركيا', '+90', true),
  (uuid_generate_v4(), 'TM', 'TKM', 'Turkménistan', 'Turkmenistan', 'تركمانستان', '+993', true),
  (uuid_generate_v4(), 'TV', 'TUV', 'Tuvalu', 'Tuvalu', 'توفالو', '+688', true),
  -- U
  (uuid_generate_v4(), 'UG', 'UGA', 'Ouganda', 'Uganda', 'أوغندا', '+256', true),
  (uuid_generate_v4(), 'UA', 'UKR', 'Ukraine', 'Ukraine', 'أوكرانيا', '+380', true),
  (uuid_generate_v4(), 'AE', 'ARE', 'Émirats arabes unis', 'United Arab Emirates', 'الإمارات العربية المتحدة', '+971', true),
  (uuid_generate_v4(), 'GB', 'GBR', 'Royaume-Uni', 'United Kingdom', 'المملكة المتحدة', '+44', true),
  (uuid_generate_v4(), 'US', 'USA', 'États-Unis', 'United States', 'الولايات المتحدة', '+1', true),
  (uuid_generate_v4(), 'UY', 'URY', 'Uruguay', 'Uruguay', 'أوروغواي', '+598', true),
  (uuid_generate_v4(), 'UZ', 'UZB', 'Ouzbékistan', 'Uzbekistan', 'أوزبكستان', '+998', true),
  -- V
  (uuid_generate_v4(), 'VU', 'VUT', 'Vanuatu', 'Vanuatu', 'فانواتو', '+678', true),
  (uuid_generate_v4(), 'VA', 'VAT', 'Vatican', 'Vatican City', 'الفاتيكان', '+379', true),
  (uuid_generate_v4(), 'VE', 'VEN', 'Venezuela', 'Venezuela', 'فنزويلا', '+58', true),
  (uuid_generate_v4(), 'VN', 'VNM', 'Viêt Nam', 'Vietnam', 'فيتنام', '+84', true),
  -- Y
  (uuid_generate_v4(), 'YE', 'YEM', 'Yémen', 'Yemen', 'اليمن', '+967', true),
  -- Z
  (uuid_generate_v4(), 'ZM', 'ZMB', 'Zambie', 'Zambia', 'زامبيا', '+260', true),
  (uuid_generate_v4(), 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwe', 'زيمبابوي', '+263', true)
ON CONFLICT (iso_code) DO UPDATE SET
  iso_code3 = EXCLUDED.iso_code3,
  name_fr = EXCLUDED.name_fr,
  name_en = EXCLUDED.name_en,
  name_ar = EXCLUDED.name_ar,
  phone_code = EXCLUDED.phone_code,
  active = true;

COMMIT;
